name: flask-application-workflow

on: push
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the Code  #Checkout the code
        uses: actions/checkout@v4
      # - name: Install Python requirements
      #   uses: aabadie/action-install-python-requirements@v2.0.1
      - name: building the package
        run: |
          python -m pip install --upgrade pip
          python3 -m pip install build
          ls
          mkdir ../python-package
          cp -r dist/* ../rc-manage
        working-directory: flask
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.6.2
        with:
          name: package
          path: rc-manage/
