name: python-application-workflow

on: push
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the Code  #Checkout the code
        uses: actions/checkout@v4
      - name: building the package
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install build
          ls
        working-directory: python-app
