name: react-application-workflow  #workflow name

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the Code  #Checkout the code
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v3.9.1
        with:
          node-version: '12'
      - name: Install in Dependencies
        run: |
         npm install
         npm run build
         mkdir -p ../artifact
         cp -arp build ../artifact
        working-directory: react-app
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.6.2
        with:
          name: package
          path: artifact/
